### ISSUE TITLE
Reference Error window is not defined when importing Provider in nextjs

### ISSUE THREAD

**Issue by MortezaT** [AxaGuilDEv/react-oidc#546]
### Issue and Steps to Reproduce

- Create a Nextjs application.
- add @axa-fr/react-oidc-context package
- import provider in _app.js `import { AuthenticationProvider } from "@axa-fr/react-oidc-context";`
- Congratulations, you have the error

The issue take place in `withRouter` and since it uses `window` even a simple import of Provider causes reference error since window is `undefined` on node server.

    ReferenceError: window is not defined
    at Object.<anonymous> (/Users/ramin/Documents/Sonbol/next-ids4/node_modules/@axa-fr/react-oidc-core/dist/routes/withRouter.js:46:38)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/ramin/Documents/Sonbol/next-ids4/node_modules/@axa-fr/react-oidc-core/dist/default-component/SessionLost.component.js:7:36)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    error - ReferenceError: window is not defined
    at Object.<anonymous> (/Users/ramin/Documents/Sonbol/next-ids4/node_modules/@axa-fr/react-oidc-core/dist/routes/withRouter.js:46:38)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/ramin/Documents/Sonbol/next-ids4/node_modules/@axa-fr/react-oidc-core/dist/default-component/SessionLost.component.js:7:36)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    ReferenceError: window is not defined
    at Object.<anonymous> (/Users/ramin/Documents/Sonbol/next-ids4/node_modules/@axa-fr/react-oidc-core/dist/routes/withRouter.js:46:38)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/ramin/Documents/Sonbol/next-ids4/node_modules/@axa-fr/react-oidc-core/dist/default-component/SessionLost.component.js:7:36)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)

### Additional Details

- Installed packages: `@axa-fr/react-oidc-context` `oidc-client`

**Comment by raminrez** [comment]
I have the same issue
`{
    "@axa-fr/react-oidc-context": "^3.1.6",
    "next": "10.0.1",
    "oidc-client": "^1.10.1",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  }`

**Comment by Reelshrimpboat** [comment]
I found a work around for now, you can use next/dynamic to load dynamically with SSR diasbled, so create a component like: 
```
import { AuthenticationProvider, oidcLog } from '@axa-fr/react-oidc-context';
import oidcConfiguration from 'constants/OidcConfig';

interface Props {
  children: React.ReactNode;
}

export default function AuthProvier(props: Props){
  const {children} = props;
  return (
    <AuthenticationProvider configuration={oidcConfiguration} loggerLevel={oidcLog.DEBUG} isEnabled={true}>
      {children}
    </AuthenticationProvider>
  )
}
```
then import to your app.jsx/tsx like:
```
import dynamic from 'next/dynamic'

const AuthProvider = dynamic(() => import('constants/AuthProvider'), {
  ssr: false
})
```
Then you can wrap anything the same way you would if you were using `<AuthenticationProvider>`. Seems like this has to be done with pretty much everything from this lib when using it in a nextJs app unfortunately

**Comment by guillaume-chervet** [comment]
Do you still have this issue with the V4?

**Comment by MortezaT** [comment]
@guillaume-chervet 
It was a project I was working on at that time and now I'm working in another company with other issues :)

**Comment by guillaume-chervet** [comment]
Thank you very much forbyour feedback. I close the issue. Feel free to reopen it if needed.

**Comment by tuhin-tsm** [comment]
@guillaume-chervet I can confirm that it's still happening. I tried this today with latest version(`"@axa-fr/react-oidc-context": "^4.2.2"`).

```
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.<anonymous>
file:///C:/.../node_modules/@axa-fr/react-oidc-context/dist/core/routes/withRouter.js (60:43)
```

**Comment by guillaume-chervet** [comment]
Thank you very much for your feedback. I will try today to reproduce it!

**Comment by dantheother** [comment]
I tried @Reelshrimpboat's solution for  5.3.1 and I'm still getting "ReferenceError: window is not defined" in next.js 12.1.5

**Comment by guillaume-chervet** [comment]
I think i will build a full demo with nextjs. It will help to maintain the compatibility and improve the documentation.

**Comment by guillaume-chervet** [comment]
This have been fixed by #789 
We still have to add a demo and documentation.

**Comment by guillaume-chervet** [comment]
I close the issue. Now it it working via the nextjs demo.
Thank you very much for all your help! Feel free to reopen it if you need.
